### ISSUE TITLE
Picking a Data Store

### ISSUE THREAD

**Issue by danfranks** [guyellis/plant#1]
Hello, my experience lies in all things data.  Emphasis on MySQL, Teradata, and Java with experience in a great many more.  I am basically a jack of all trades researching whatever I need to implement solutions.

I have not worked with IBM's Cloudant but it looks like pretty much every other NoSQL DBaaS.  lol  Why would you want NoSQL for this project?  It seems more geared at an OLTP / relational database architecture.

**Comment by guyellis** [comment]
Hi @danfranks - would love your input and help with the data or any other aspect of this project. My thought process is:

* DBaaS because I don't want to manage a DB.
* Cloudant because
  * it's based on CouchDB and has great features for syncying after a disconnect. Would allow users to continue operating in an offline mode. (Not 100% certain if this is a feature that would be usable as it might need to be the app that implements that feature.)
  * Has very good GeoSpacial features that would allow the "find another within X miles of me" feature.
* NoSQL in the early stages because we'll be adding a lot of new structured data to the records at each iteration and it's less painful in NoSQL.

Let me know your thoughts.

**Comment by danfranks** [comment]
That makes a lot of sense. Especially with your heavy emphasis in JS.  I was going to suggest MongoDB but I think CouchDB is probably the way to go as well.  I sometimes forget that NoSQL is also good for small projects. I am used to using it only for very large data stores attached to data warehouses.

If you want to avoid having to pay for a DBaaS, I could throw CouchDB up on my digital ocean VPS.  I would love to do this for the learning experience.  I could create an account for you and also script in a backup that emails you a copy or drops it on dropbox in case I get hit by bus or something.  :)

**Comment by guyellis** [comment]
I think that IBM's Cloudant is CouchDB + Lucene (+ perhaps other stuff I don't know about). I think that the GeoSpacial stuff in CouchDB is enhanced or provided by Lucene. (I'm also still learning more about this.)

If you don't consume more than $50/month in services from Cloudant then it's free. So you can setup an account and run directly against that for free.

**Comment by danfranks** [comment]
Well there you go!  Sounds good.

**Comment by guyellis** [comment]
From my initial work with Cloudant it seems to be working well for this application so I'm going to close this issue. We can reopen it if we need to revisit this.
