### ISSUE TITLE
Drop jQuery

### ISSUE THREAD

**Issue by guyellis** [guyellis/plant#2920]
I think this is only being used for:

- image uploads
- ajax methods

For images switch this to direct loading to S3.

For ajax use `fetch` or equivalent: https://tobiasahlin.com/blog/move-from-jquery-to-vanilla-javascript/#network-requests-with-get-or-ajax

**Comment by robrich** [comment]
http://youmightnotneedjquery.com/ is a great resource for flipping to
Vanilla.js

>

**Comment by robrich** [comment]
Bootstrap 3 (and bootstrap 4) still use jQuery behind the scenes, but because you're using react-bootstrap (not the bootstrap javascript) you should be fine.

 

The fetch api doesn't seem to provide upload progress, but axios does.  Alternatively, be content not to see progress from https://github.com/guyellis/plant/blob/cdce477533224dda91264b7d9d9aaf14023ca812/app/middleware/api.ts#L94
