### ISSUE TITLE
RSS Feed

### ISSUE THREAD

**Issue by guyellis** [guyellis/plant#888]
We need an RSS Feed to expose the latest notes that have been added.

Or is the answer to create a Twitter account and post a summary and link to each Note added?

**Comment by guyellis** [comment]
Some of the comments that I remember from our chat @sprise 

- Create a /lib/routes/rss.js file and wire it up like the other files in /lib/routes/
- There's probably a Node rss helper module in Npm that can be used for creating the output.
- Need to make a call to DB to get the most recent N notes. Probably also need to make calls to the DB to get the corresponding plant records for those notes so that a link to the relevant Plant can be created.
- Will need to do a server side render of the /app/components/plant/NoteRead.jsx file. Use a copy of /lib/render/plant.js as the starting point for this.

**Comment by sprise** [comment]
I wrote the rss-feed branch and didn't remember this thread... Luckily I did many of those things but not all. Have renamed the branch with this issue #. 

A fair bit of tweaking to get it to pass the linter. Mostly it took umbrage with + concatenation and spacing. Also you never really know how many trailing spaces are in there (with the visual marker turned off) until jslint digs them all up for you ;) I still don't know where they come from!

I tend to write a generous amount of comments, and I've noted a few things in the branch that I thought could be important. Like the date string format to output the correct date, instead of being one day behind. Although other comments were me trying to just pass the linter. 

You can probably tell that I have recently become acquainted with .map() & friends. This seemed like a great solution for iterating over the notes but it did feel wrong having to add bogus return statements just to pass the linter. On one occasion I switch to a for loop to be able to assign properties without error. Some other way that would have been preferred there?

**Comment by guyellis** [comment]
This is awesome work @sprise - I'm working through the code in this branch now and will hopefully do a PR later.

One of the items that I just came across was getting the Notes from the DB and sorting by most recent which makes complete sense from wanting to see the most recent chronological notes that have been added. However it will miss all of the notes that have been retrospectively added by a user. I don't know what the answer is though.

i.e. if a user has a blog and writes a blog post and dates it 2 years ago and there are say 50 posts with subsequent dates will that 2-year-old blog post appear in the RSS feed? We that depends on how the RSS feed is written. If each blog post has a (1) date, (2) createdDate, and (3) lastModifiedDate then the RSS feed could use any of those dates for sorting. If it were to use date then it would not show up in the last 20. If it were to use createdDate/lastModifiedDate it would.

I think we leave it as is for now. Just something to think about.

**Comment by guyellis** [comment]
@sprise another thing I just thought of is that we might want to filter the RSS feel by location. This should be easy to add later. Currently the RSS feed is `/rss`. To add by location we could add an optional location ID so it would be `/rss/location-id`
